on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master
    tags:
      - 'v**'

name: e2e
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        globalnet: ['',]
        deploytool: ['--deploytool operator']
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Install packages
        run: |
          sudo add-apt-repository -y ppa:wireguard/wireguard # add WireGuard support
          sudo apt-get update
          sudo apt-get install wireguard -y

      - name: run E2E
        run: |
          set -o pipefail
          make e2e CLUSTER_ARGS="${{ matrix.globalnet }}" DEPLOY_ARGS="${{ matrix.globalnet }} ${{ matrix.deploytool }}"

